version: '3.7'

networks:
  docker_network:
    name: ${NETWORK}

services:

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    networks:
      docker_network:
    environment:
      ADMINER_PLUGINS: ${ADMINER_PLUGINS}
      ADMINER_DESIGN: ${ADMINER_DESIGN}
    ports:
      - ${ADMINER_PORT}:8080

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      docker_network:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./runtime/mongo:/data/db
      - ./mongo/mongodb.conf:/etc/mongodb.conf
    ports:
      - "${MONGO_PORT}:27017-27019"